#pragma once

#define BUTTON_STATUS_FALSE				0x00
#define BUTTON_STATUS_TRUE				0x01
#define BUTTON_STATUS_SELECT			0x02
#define BUTTON_STATUS_ACTIVE			0x04 //Button can change by click.
#define BUTTON_STATUS_CUSTOM_RED		0x08
#define BUTTON_STATUS_CUSTOM_GREEN		0x10
#define BUTTON_STATUS_CUSTOM_BLUE		0x20
#define BUTTON_STATUS_CUSTOM_PURPURE	0x40
#define BUTTON_STATUS_CUSTOM_5			0x80
#define BUTTON_STATUS_ALL				0xFF

#define CAMERA_DEFAULT_POSITION Vec2F()
#define CAMERA_DEFAULT_SCALE    1.0f
#define CAMERA_DEFAULT_SIZE     1.0f

