#pragma once

#define POINT_DEFAULT_NUMBER    0u
#define POINT_DEFAULT_POSITION  Vec2F()
#define POINT_DEFAULT_RADIUS    1.0f
#define POINT_NORMAL_TEXT_SIZE  270.0f
#define POINT_MAX_TEXT_SIZE     90.0f
#define POINT_TEXT_SIZE_AUTO    (0.0f / 0.0f)

#define CONNECTION_ANGLE_TG     0.03f

#define CONNECTION_DEFAULT_DISTANCE_TO_POINT    0.1f
#define CONNECTION_DEFAULT_SHIFT  0.0f

#define CONNECTION_LOOP_ROTATE  3.3f

#define CONNECTION_SEGMENT_ID_CENTER    0u
#define CONNECTION_SEGMENT_ID_START     1u
#define CONNECTION_SEGMENT_ID_END       2u
      



